# Generated by Django 5.2.7 on 2025-10-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
    ]
